gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title
paginate: 10
exclude: [
 'node_modules',
 '.gitignore',
 'README.md',
 'Gruntfile.js',
 'bigandy.github.sublime-project',
 'package.json',
 'jquery.js',
 'js/demos',
 'js/libs/**/*.html'
 ]
sass:
 style: :compressed
