markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title
paginate: 10
exclude: [
 'node_modules',
 '.gitignore',
 'README.md',
 'Gruntfile.js',
 'bigandy.github.sublime-project',
 'package.json',
 'jquery.js',
 'js/demos'
 ]
include: [
 '.htaccess'
]